version: "3.9"
services:
  mysql:
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - mysql-data:/var/lib/mysql/data
    ports:
      - 3306:3306
volumes:
  mysql-data:
